### ISSUE TITLE
python 3 support?

### ISSUE THREAD

**Issue by xylar** [CDAT/e3sm_nex#1]
I'm wondering if this package supports python 3.x and packages just haven't yet been uploaded to the cdat channel?  https://anaconda.org/cdat/e3sm_nex/files

I'm working on a python 3.6 version of [e3sm-unified](https://github.com/E3SM-Project/e3sm-unified/pull/10) and would need a python 3.6 version of all its dependencies.  `e3sm_nex` is the first one to give me trouble that I haven't been able to solve on my own.

**Comment by doutriaux1** [comment]
@xylar I didn't bother try on Python3 since so far E3SM didn't need it. I'll double check and upload PY3 binaries shortly.

**Comment by doutriaux1** [comment]
@xylar version `0.0.2` is out and supports python 3. Please update e3sm_unified to get this version. It supports MPAS grids.

**Comment by xylar** [comment]
Thanks!
